import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
   faUser,
   faCat,
   faDog,
   faFish,
   faDove,
   faCrow,
   faDragon,
   faHippo,
   faOtter,
   faFrog,
   faSpider,
   faHorse,
   faKiwiBird,
   faShrimp,
   faWorm,
   faBugs,
   faOwl,
   faButterfly,
   faFeather,
   faPawSimple,
   faAlicorn,
   faCrab,
   faWhale,
   faElephant,
   faDeer,
   faSnake,
   faSquirrel,
   faMonkey,
   faTurtle,
   faRabbit,
   faBee,
   faBird,
   faBadgerHoney,
   faDinosaur,
   faDolphin,
   faDuck,
   faLobster,
   faNarwhal,
   faPig,
   faRam,
   faSheep,
   faCards,
   faClub,
   faDiamond,
   faSpade,
   faHeart,
   faDice,
   faCrown,
   faChessQueen,
   faMoon,
   faMoonStars,
   faSunBright,
   faStar,
   faMeteor,
   faCloudBolt,
   faSnowflake,
   faRainbow,
   faRocket,
   faLeaf,
   faSeedling,
   faTree,
   faClover,
   faFlowerTulip,
   faMountainSun,
   faMugHot,
   faPizzaSlice,
   faCookie,
   faBowlChopsticksNoodles,
   faIceCream,
   faCandyCane,
   faLemon,
   faAppleWhole,
   faPepperHot,
   faMartiniGlassCitrus,
   faWineGlass,
   faBurger,
   faCheese,
   faCherries,
   faCroissant,
   faCupcake,
   faEgg,
   faGrapes,
   faHotdog,
   faPopcorn,
   faTaco,
   faMusic,
   faGuitar,
   faDrum,
   faPalette,
   faPaintbrushFine,
   faHeadphones,
   faGhost,
   faHatWizard,
   faWandMagicSparkles,
   faGem,
   faFire,
   faBolt,
   faShield,
   faSkullCrossbones,
   faBinoculars,
   faCompass,
   faAnchor,
   faBomb,
   faSwords,
   faAxeBattle,
   faKey,
   faDagger,
   faHourglass,
   faScroll,
   faRing,
   faFlask,
   faTelescope,
   faFaceSmile,
   faFaceSunglasses,
   faFaceCowboyHat,
   faFaceParty,
   faCakeCandles,
   faGift,
   faBalloon,
   faSparkles,
   faFutbol,
   faBasketball,
   faBicycle,
   faPersonSkiing,
   faFishFins,
   faGamepad,
   faJackOLantern,
   faBat,
   faSnowman,
   faGifts,
   faHatSanta,
   faCauldron,
   faYinYang,
   faPeace,
   faInfinity,
   faEye,
   faHandSpock,
   faAlien8bit,
   faUserAstronaut,
   faUserNinja,
   faUserRobot,
   faCode,
   faTerminal,
   faLaptopCode,
   faBug,
   faMicrochip,
   faBinary,
   faDatabase,
   faKeyboard,
   faGamepadModern,
   faChessPawn,
   faChessKnight,
   faDiceD20,
   faSwordLaser,
   faUfo,
   faJoystick,
   faChessRook,
   faCloudMoon,
   faComet,
   faCactus,
   faMushroom,
   faTreePalm,
   faFlowerDaffodil,
   faMicrophoneStand,
   faRecordVinyl,
   faRadio,
   faPiano,
   faFaceLaughBeam,
   faBaseballBatBall,
   faTennisBall,
   faTableTennisPaddleBall,
   faPersonSwimming,
   faPersonRunning,
   faBowlingBall,
   faServer,
   faBracketsCurly,
   faPuzzlePiece,
   faTreasureChest,
   faAtom,
   faDna,
   faOm,
   faGingerbreadMan,
   faStocking,
   faChessBishop,
} from "@fortawesome/pro-solid-svg-icons";

export interface ProfileIconEntry {
   key: string;
   label: string;
   icon: IconDefinition;
   category: string;
}

export const PROFILE_ICON_CATEGORIES = [
   "Animals",
   "Food & Drink",
   "Gaming",
   "Space & Weather",
   "Nature",
   "Music & Art",
   "Fun Objects",
   "Cute",
   "Sports",
   "Coding",
   "Holiday",
   "Symbols",
] as const;

export const PROFILE_ICONS: ProfileIconEntry[] = [
   // Animals
   { key: "alicorn", label: "Alicorn", icon: faAlicorn, category: "Animals" },
   {
      key: "badger-honey",
      label: "Badger",
      icon: faBadgerHoney,
      category: "Animals",
   },
   { key: "bee", label: "Bee", icon: faBee, category: "Animals" },
   { key: "bird", label: "Bird", icon: faBird, category: "Animals" },
   { key: "bugs", label: "Bugs", icon: faBugs, category: "Animals" },
   {
      key: "butterfly",
      label: "Butterfly",
      icon: faButterfly,
      category: "Animals",
   },
   { key: "cat", label: "Cat", icon: faCat, category: "Animals" },
   { key: "crab", label: "Crab", icon: faCrab, category: "Animals" },
   { key: "crow", label: "Crow", icon: faCrow, category: "Animals" },
   { key: "deer", label: "Deer", icon: faDeer, category: "Animals" },
   {
      key: "dinosaur",
      label: "Dinosaur",
      icon: faDinosaur,
      category: "Animals",
   },
   { key: "dog", label: "Dog", icon: faDog, category: "Animals" },
   { key: "dove", label: "Dove", icon: faDove, category: "Animals" },
   { key: "dragon", label: "Dragon", icon: faDragon, category: "Animals" },
   { key: "dolphin", label: "Dolphin", icon: faDolphin, category: "Animals" },
   { key: "duck", label: "Duck", icon: faDuck, category: "Animals" },
   {
      key: "elephant",
      label: "Elephant",
      icon: faElephant,
      category: "Animals",
   },
   { key: "feather", label: "Feather", icon: faFeather, category: "Animals" },
   { key: "fish", label: "Fish", icon: faFish, category: "Animals" },
   { key: "frog", label: "Frog", icon: faFrog, category: "Animals" },
   { key: "hippo", label: "Hippo", icon: faHippo, category: "Animals" },
   { key: "horse", label: "Horse", icon: faHorse, category: "Animals" },
   {
      key: "kiwi-bird",
      label: "Kiwi Bird",
      icon: faKiwiBird,
      category: "Animals",
   },
   { key: "lobster", label: "Lobster", icon: faLobster, category: "Animals" },
   { key: "monkey", label: "Monkey", icon: faMonkey, category: "Animals" },
   { key: "narwhal", label: "Narwhal", icon: faNarwhal, category: "Animals" },
   { key: "otter", label: "Otter", icon: faOtter, category: "Animals" },
   { key: "owl", label: "Owl", icon: faOwl, category: "Animals" },
   { key: "paw-simple", label: "Paw", icon: faPawSimple, category: "Animals" },
   { key: "pig", label: "Pig", icon: faPig, category: "Animals" },
   { key: "rabbit", label: "Rabbit", icon: faRabbit, category: "Animals" },
   { key: "ram", label: "Ram", icon: faRam, category: "Animals" },
   { key: "sheep", label: "Sheep", icon: faSheep, category: "Animals" },
   { key: "shrimp", label: "Shrimp", icon: faShrimp, category: "Animals" },
   { key: "snake", label: "Snake", icon: faSnake, category: "Animals" },
   { key: "spider", label: "Spider", icon: faSpider, category: "Animals" },
   {
      key: "squirrel",
      label: "Squirrel",
      icon: faSquirrel,
      category: "Animals",
   },
   { key: "turtle", label: "Turtle", icon: faTurtle, category: "Animals" },
   { key: "whale", label: "Whale", icon: faWhale, category: "Animals" },
   { key: "worm", label: "Worm", icon: faWorm, category: "Animals" },

   // Gaming
   { key: "cards", label: "Cards", icon: faCards, category: "Gaming" },
   { key: "club", label: "Club", icon: faClub, category: "Gaming" },
   { key: "diamond", label: "Diamond", icon: faDiamond, category: "Gaming" },
   { key: "spade", label: "Spade", icon: faSpade, category: "Gaming" },
   { key: "heart", label: "Heart", icon: faHeart, category: "Gaming" },
   { key: "dice", label: "Dice", icon: faDice, category: "Gaming" },
   { key: "crown", label: "Crown", icon: faCrown, category: "Gaming" },
   {
      key: "chess-queen",
      label: "Queen",
      icon: faChessQueen,
      category: "Gaming",
   },
   { key: "chess-rook", label: "Rook", icon: faChessRook, category: "Gaming" },
   {
      key: "chess-bishop",
      label: "Bishop",
      icon: faChessBishop,
      category: "Gaming",
   },
   { key: "gamepad", label: "Gamepad", icon: faGamepad, category: "Gaming" },
   {
      key: "gamepad-modern",
      label: "Controller",
      icon: faGamepadModern,
      category: "Gaming",
   },
   {
      key: "chess-pawn",
      label: "Chess Pawn",
      icon: faChessPawn,
      category: "Gaming",
   },
   {
      key: "chess-knight",
      label: "Chess Knight",
      icon: faChessKnight,
      category: "Gaming",
   },
   { key: "dice-d20", label: "D20", icon: faDiceD20, category: "Gaming" },
   {
      key: "sword-laser",
      label: "Laser Sword",
      icon: faSwordLaser,
      category: "Gaming",
   },
   { key: "ufo", label: "UFO", icon: faUfo, category: "Gaming" },
   { key: "joystick", label: "Joystick", icon: faJoystick, category: "Gaming" },
   {
      key: "puzzle-piece",
      label: "Puzzle",
      icon: faPuzzlePiece,
      category: "Gaming",
   },
   {
      key: "bowling-ball",
      label: "Bowling",
      icon: faBowlingBall,
      category: "Gaming",
   },

   // Space & Weather
   { key: "moon", label: "Moon", icon: faMoon, category: "Space & Weather" },
   {
      key: "moon-stars",
      label: "Moon Stars",
      icon: faMoonStars,
      category: "Space & Weather",
   },
   {
      key: "sun-bright",
      label: "Sun",
      icon: faSunBright,
      category: "Space & Weather",
   },
   { key: "star", label: "Star", icon: faStar, category: "Space & Weather" },
   {
      key: "meteor",
      label: "Meteor",
      icon: faMeteor,
      category: "Space & Weather",
   },
   {
      key: "cloud-bolt",
      label: "Lightning",
      icon: faCloudBolt,
      category: "Space & Weather",
   },
   {
      key: "snowflake",
      label: "Snowflake",
      icon: faSnowflake,
      category: "Space & Weather",
   },
   {
      key: "rainbow",
      label: "Rainbow",
      icon: faRainbow,
      category: "Space & Weather",
   },
   {
      key: "rocket",
      label: "Rocket",
      icon: faRocket,
      category: "Space & Weather",
   },
   { key: "comet", label: "Comet", icon: faComet, category: "Space & Weather" },

   // Nature
   { key: "leaf", label: "Leaf", icon: faLeaf, category: "Nature" },
   { key: "seedling", label: "Seedling", icon: faSeedling, category: "Nature" },
   { key: "tree", label: "Tree", icon: faTree, category: "Nature" },
   { key: "clover", label: "Clover", icon: faClover, category: "Nature" },
   {
      key: "flower-tulip",
      label: "Tulip",
      icon: faFlowerTulip,
      category: "Nature",
   },
   {
      key: "mountain-sun",
      label: "Mountain",
      icon: faMountainSun,
      category: "Nature",
   },
   { key: "cactus", label: "Cactus", icon: faCactus, category: "Nature" },
   { key: "mushroom", label: "Mushroom", icon: faMushroom, category: "Nature" },
   {
      key: "tree-palm",
      label: "Palm Tree",
      icon: faTreePalm,
      category: "Nature",
   },
   {
      key: "flower-daffodil",
      label: "Daffodil",
      icon: faFlowerDaffodil,
      category: "Nature",
   },

   // Food & Drink
   {
      key: "mug-hot",
      label: "Hot Mug",
      icon: faMugHot,
      category: "Food & Drink",
   },
   {
      key: "pizza-slice",
      label: "Pizza",
      icon: faPizzaSlice,
      category: "Food & Drink",
   },
   { key: "cookie", label: "Cookie", icon: faCookie, category: "Food & Drink" },
   {
      key: "ice-cream",
      label: "Ice Cream",
      icon: faIceCream,
      category: "Food & Drink",
   },
   { key: "lemon", label: "Lemon", icon: faLemon, category: "Food & Drink" },
   {
      key: "apple-whole",
      label: "Apple",
      icon: faAppleWhole,
      category: "Food & Drink",
   },
   {
      key: "pepper-hot",
      label: "Hot Pepper",
      icon: faPepperHot,
      category: "Food & Drink",
   },
   {
      key: "ramen",
      label: "Ramen",
      icon: faBowlChopsticksNoodles,
      category: "Food & Drink",
   },
   {
      key: "martini-glass-citrus",
      label: "Cocktail",
      icon: faMartiniGlassCitrus,
      category: "Food & Drink",
   },
   {
      key: "wine-glass",
      label: "Wine",
      icon: faWineGlass,
      category: "Food & Drink",
   },
   { key: "burger", label: "Burger", icon: faBurger, category: "Food & Drink" },
   { key: "cheese", label: "Cheese", icon: faCheese, category: "Food & Drink" },
   {
      key: "cherries",
      label: "Cherries",
      icon: faCherries,
      category: "Food & Drink",
   },
   {
      key: "croissant",
      label: "Croissant",
      icon: faCroissant,
      category: "Food & Drink",
   },
   {
      key: "cupcake",
      label: "Cupcake",
      icon: faCupcake,
      category: "Food & Drink",
   },
   { key: "egg", label: "Egg", icon: faEgg, category: "Food & Drink" },
   { key: "grapes", label: "Grapes", icon: faGrapes, category: "Food & Drink" },
   { key: "hotdog", label: "Hotdog", icon: faHotdog, category: "Food & Drink" },
   {
      key: "popcorn",
      label: "Popcorn",
      icon: faPopcorn,
      category: "Food & Drink",
   },
   { key: "taco", label: "Taco", icon: faTaco, category: "Food & Drink" },

   // Music & Art
   { key: "music", label: "Music", icon: faMusic, category: "Music & Art" },
   { key: "guitar", label: "Guitar", icon: faGuitar, category: "Music & Art" },
   { key: "drum", label: "Drum", icon: faDrum, category: "Music & Art" },
   {
      key: "palette",
      label: "Palette",
      icon: faPalette,
      category: "Music & Art",
   },
   {
      key: "paintbrush-fine",
      label: "Paintbrush",
      icon: faPaintbrushFine,
      category: "Music & Art",
   },
   {
      key: "headphones",
      label: "Headphones",
      icon: faHeadphones,
      category: "Music & Art",
   },
   {
      key: "microphone-stand",
      label: "Microphone",
      icon: faMicrophoneStand,
      category: "Music & Art",
   },
   {
      key: "record-vinyl",
      label: "Vinyl",
      icon: faRecordVinyl,
      category: "Music & Art",
   },
   { key: "radio", label: "Radio", icon: faRadio, category: "Music & Art" },
   { key: "piano", label: "Piano", icon: faPiano, category: "Music & Art" },

   // Fun Objects
   {
      key: "hat-wizard",
      label: "Wizard Hat",
      icon: faHatWizard,
      category: "Fun Objects",
   },
   {
      key: "wand-magic-sparkles",
      label: "Magic Wand",
      icon: faWandMagicSparkles,
      category: "Fun Objects",
   },
   { key: "gem", label: "Gem", icon: faGem, category: "Fun Objects" },
   { key: "fire", label: "Fire", icon: faFire, category: "Fun Objects" },
   { key: "bolt", label: "Bolt", icon: faBolt, category: "Fun Objects" },
   { key: "shield", label: "Shield", icon: faShield, category: "Fun Objects" },
   {
      key: "skull-crossbones",
      label: "Skull",
      icon: faSkullCrossbones,
      category: "Fun Objects",
   },
   {
      key: "binoculars",
      label: "Binoculars",
      icon: faBinoculars,
      category: "Fun Objects",
   },
   {
      key: "compass",
      label: "Compass",
      icon: faCompass,
      category: "Fun Objects",
   },
   { key: "anchor", label: "Anchor", icon: faAnchor, category: "Fun Objects" },
   { key: "bomb", label: "Bomb", icon: faBomb, category: "Fun Objects" },
   { key: "swords", label: "Swords", icon: faSwords, category: "Fun Objects" },
   {
      key: "axe-battle",
      label: "Battle Axe",
      icon: faAxeBattle,
      category: "Fun Objects",
   },
   { key: "key", label: "Key", icon: faKey, category: "Fun Objects" },
   { key: "dagger", label: "Dagger", icon: faDagger, category: "Fun Objects" },
   {
      key: "hourglass",
      label: "Hourglass",
      icon: faHourglass,
      category: "Fun Objects",
   },
   { key: "scroll", label: "Scroll", icon: faScroll, category: "Fun Objects" },
   { key: "ring", label: "Ring", icon: faRing, category: "Fun Objects" },
   { key: "flask", label: "Flask", icon: faFlask, category: "Fun Objects" },
   {
      key: "telescope",
      label: "Telescope",
      icon: faTelescope,
      category: "Fun Objects",
   },

   // Cute / Whimsical
   { key: "face-smile", label: "Smiley", icon: faFaceSmile, category: "Cute" },
   {
      key: "face-sunglasses",
      label: "Sunglasses",
      icon: faFaceSunglasses,
      category: "Cute",
   },
   {
      key: "face-cowboy-hat",
      label: "Cowboy",
      icon: faFaceCowboyHat,
      category: "Cute",
   },
   { key: "face-party", label: "Party", icon: faFaceParty, category: "Cute" },
   {
      key: "cake-candles",
      label: "Cake",
      icon: faCakeCandles,
      category: "Cute",
   },
   { key: "gift", label: "Gift", icon: faGift, category: "Cute" },
   { key: "balloon", label: "Balloon", icon: faBalloon, category: "Cute" },
   { key: "sparkles", label: "Sparkles", icon: faSparkles, category: "Cute" },
   {
      key: "face-laugh-beam",
      label: "Laughing",
      icon: faFaceLaughBeam,
      category: "Cute",
   },
   {
      key: "treasure-chest",
      label: "Treasure",
      icon: faTreasureChest,
      category: "Cute",
   },

   // Sports
   { key: "futbol", label: "Soccer", icon: faFutbol, category: "Sports" },
   {
      key: "basketball",
      label: "Basketball",
      icon: faBasketball,
      category: "Sports",
   },
   { key: "bicycle", label: "Bicycle", icon: faBicycle, category: "Sports" },
   {
      key: "person-skiing",
      label: "Skiing",
      icon: faPersonSkiing,
      category: "Sports",
   },
   {
      key: "fish-fins",
      label: "Fish Fins",
      icon: faFishFins,
      category: "Sports",
   },
   {
      key: "baseball-bat-ball",
      label: "Baseball",
      icon: faBaseballBatBall,
      category: "Sports",
   },
   {
      key: "tennis-ball",
      label: "Tennis",
      icon: faTennisBall,
      category: "Sports",
   },
   {
      key: "table-tennis-paddle-ball",
      label: "Ping Pong",
      icon: faTableTennisPaddleBall,
      category: "Sports",
   },
   {
      key: "person-swimming",
      label: "Swimming",
      icon: faPersonSwimming,
      category: "Sports",
   },
   {
      key: "person-running",
      label: "Running",
      icon: faPersonRunning,
      category: "Sports",
   },

   // Coding
   { key: "code", label: "Code", icon: faCode, category: "Coding" },
   { key: "terminal", label: "Terminal", icon: faTerminal, category: "Coding" },
   {
      key: "laptop-code",
      label: "Laptop",
      icon: faLaptopCode,
      category: "Coding",
   },
   { key: "bug", label: "Bug", icon: faBug, category: "Coding" },
   {
      key: "microchip",
      label: "Microchip",
      icon: faMicrochip,
      category: "Coding",
   },
   { key: "binary", label: "Binary", icon: faBinary, category: "Coding" },
   { key: "database", label: "Database", icon: faDatabase, category: "Coding" },
   { key: "keyboard", label: "Keyboard", icon: faKeyboard, category: "Coding" },
   { key: "server", label: "Server", icon: faServer, category: "Coding" },
   {
      key: "brackets-curly",
      label: "Brackets",
      icon: faBracketsCurly,
      category: "Coding",
   },

   // Holiday
   { key: "bat", label: "Bat", icon: faBat, category: "Holiday" },
   {
      key: "jack-o-lantern",
      label: "Pumpkin",
      icon: faJackOLantern,
      category: "Holiday",
   },
   { key: "ghost", label: "Ghost", icon: faGhost, category: "Holiday" },
   {
      key: "candy-cane",
      label: "Candy Cane",
      icon: faCandyCane,
      category: "Holiday",
   },
   { key: "snowman", label: "Snowman", icon: faSnowman, category: "Holiday" },
   { key: "gifts", label: "Gifts", icon: faGifts, category: "Holiday" },
   {
      key: "hat-santa",
      label: "Santa Hat",
      icon: faHatSanta,
      category: "Holiday",
   },
   {
      key: "cauldron",
      label: "Cauldron",
      icon: faCauldron,
      category: "Holiday",
   },
   {
      key: "gingerbread-man",
      label: "Gingerbread",
      icon: faGingerbreadMan,
      category: "Holiday",
   },
   {
      key: "stocking",
      label: "Stocking",
      icon: faStocking,
      category: "Holiday",
   },

   // Symbols
   { key: "yin-yang", label: "Yin Yang", icon: faYinYang, category: "Symbols" },
   { key: "peace", label: "Peace", icon: faPeace, category: "Symbols" },
   {
      key: "infinity",
      label: "Infinity",
      icon: faInfinity,
      category: "Symbols",
   },
   { key: "eye", label: "Eye", icon: faEye, category: "Symbols" },
   {
      key: "hand-spock",
      label: "Spock",
      icon: faHandSpock,
      category: "Symbols",
   },
   {
      key: "alien-8bit",
      label: "Alien",
      icon: faAlien8bit,
      category: "Symbols",
   },
   {
      key: "user-astronaut",
      label: "Astronaut",
      icon: faUserAstronaut,
      category: "Symbols",
   },
   {
      key: "user-ninja",
      label: "Ninja",
      icon: faUserNinja,
      category: "Symbols",
   },
   { key: "atom", label: "Atom", icon: faAtom, category: "Symbols" },
   { key: "om", label: "Om", icon: faOm, category: "Symbols" },
];

const ICON_MAP = new Map<string, IconDefinition>(
   PROFILE_ICONS.map((e) => [e.key, e.icon])
);
ICON_MAP.set("user", faUser);
ICON_MAP.set("robot", faUserRobot);

export function getProfileIcon(key: string | undefined | null): IconDefinition {
   if (!key) return faUser;
   return ICON_MAP.get(key) ?? faUser;
}
